services:
  bot:
    build: .
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=${APP_ID}
      - POSTGRES_USER=${APP_ID}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENDART_API_KEY=${OPENDART_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}

  db:
    build:
      context: ./db
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${APP_ID}
      - POSTGRES_USER=${APP_ID}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
    restart: always

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    restart: always

volumes:
  db-data:
